### PR TITLE
Lithium + various update

### PR DESCRIPTION
**Pull request by utaninja**
I have created Lithium + various different psychedelic drug interactions and listed them as dangerous.

There is an extensive amount of reports on this combination, many of which have resulted in hospitalizations, seizures, and psychosis.

This has been demonstrated and discussed here:
https://pubmed.ncbi.nlm.nih.gov/34348413/
https://erowid.org/chemicals/lsd/lsd_interactions.shtml

Anectodal reports:
https://erowid.org/experiences/exp.php?ID=93681
https://erowid.org/experiences/exp.php?ID=110780

Study also mentions increased risk:
https://www.sciencedirect.com/science/article/pii/S0165032723000915

### CODE REVIEW

**Comment by utaninja** [comment]
Not sure if we would want to adjust the wording of the actual interaction but it is a initial suggestion for it.

**Comment by LunaUrsa** [comment]
Is this the same across all psychedelics? Nbomes, mushrooms, 2c-x, LSX etc?

**Comment by utaninja** [comment]
This was my bad to create a pull request for noting the interaction of "all" psychedelics and with Lithium. I have expanded the interaction to clarify which it is in regards to, notably excluding 5-MeO-xxT as explained in the comment for the pull request.

To forward what was written-
"I have revised my mistake of writing psychedelics for the combination.

This has the expansion of detailing Lithium's interaction with serotonergic psychedelics, excluding 5-MeO-xxT

Interactions created-
Lithium + 2C-T-x
Lithium + 2C-x
Lithium + DMT
Lithium + DOx
Lithium + LSD
Lithium + Mescaline
Lithium + Mushrooms

* 5-MeO-xxT does not have any reporting of interaction concerns and I do not feel comfortable fully stating it has a dangerous interaction with Lithium without further research."

I would also ask someone to review the code before pushing it, as I am new to JS.

**Comment by LunaUrsa** [comment]
Wonderful, thank you for that clarification!

I'm working on some database changes and can add this in, appreciate you doing the bulk of it =D

**Pull request merged**
